# Generated by Django 5.1.2 on 2024-10-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fyv',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('temporada', models.CharField(max_length=20)),
                ('calorias', models.IntegerField()),
                ('vitaminas', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('stack', models.IntegerField()),
            ],
        ),
    ]
